### ISSUE TITLE
CassandraJolokia Should be the Only Compatibility

### ISSUE THREAD

**Issue by dgeorg42** [netuitive-community-packages/netuitive-packages-cassandra#3]
@Createor - Thanks for correcting the compatibility mistakes I had in some of the _package.json files_. For Cassandra, however, the compatibility should actually be ONLY for CassandraJolokia. The metric names are completely different between the old collector (Cassandra) and the new collector (CassandraJolokia) and the package is built specifically for the new.

**Comment by Grumblesmith** [comment]
Thanks for the clarification @dgeorg42 . I'll push out that update shortly.
